{{- if not .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-lb
spec:
  selector:
    app: {{ .Values.name | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
{{- end }}


