apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: "mongodb://root:Kl6k1gnrSJ@mongo-mongodb-0.mongo-mongodb-headless,mongo-mongodb-1.mongo-mongodb-headless,mongo-mongodb-2.mongo-mongodb-headless?replicaSet=rs0"  #Refernce
  log_level: "info"
  presistence: "true"

