apiVersion: v1
kind: Secret
metadata:
  name: appsecret
type: Opaque
data:
  DB_URL: bW9uZ29kYjovL3Jvb3Q6S2w2azFnbnJTSkBtb25nby1tb25nb2RiLTAubW9uZ28tbW9uZ29kYi1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3LG1vbmdvLW1vbmdvZGItMS5tb25nby1tb25nb2RiLWhlYWRsZXNzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsbW9uZ28tbW9uZ29kYi0yLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNwo=
  DB_USER: cm9vdAo=
  DB_PASS: S2w2azFnbnJTSgo=
