apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-crm
  name: demo-crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - image: pwstaging/demo-crm:latest
        name: demo-crm
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: demo-crm-conf
